add change-id hook fetching and make SSH logic make sense

diff --git a/git-gerrit b/git-gerrit
--- a/git-gerrit
+++ b/git-gerrit
@@ -93,20 +93,26 @@ parse_config() {
     fi
 
     if ! config exist remote.gerrit.url;then
-        nonfatal dossh >/dev/null 2>&1
-        if [[ "$?" -eq 127 ]];then
+        nonfatal dossh gerrit >/dev/null 2>&1
+        if [[ "$?" -eq 0 ]];then
             debug "Connected to ${gerrit_username}@${gerrit_host}:${gerrit_port} successfully"
             gerrit_url="ssh://${gerrit_username}@${gerrit_host}:${gerrit_port}/${gerrit_project}.git"
         else
-            die "SSH connection to ${gerrit_username}@${gerrit_host}:${gerrit_port} failed!" $err_ssh_failed
+            die "SSH connection to ${gerrit_username}@${gerrit_host}:${gerrit_port} failed" $err_ssh_failed
         fi
 
         stderr "Adding a remote named \"gerrit\" pointing to \"$gerrit_url\"..."
         git remote add gerrit "${gerrit_url}"
     else
         gerrit_url=$(config get remote.gerrit.url | sed "s#/${gerrit_project}.*##;s#.*://##")
-        gerrit_type=$(config get remote.gerrit.url | sed 's#://.*##')
-        debug "Gerrit instance: \"$gerrit_url\" (type: $gerrit_type)"
+        debug "$me: Gerrit instance: \"$gerrit_url\""
+    fi
+    if [[ ! -f "${git_dir}/hooks/commit-msg" ]];then
+        debug "$me: getting commit-msg hook for Change-Id lines from \"${gerrit_url}\"..."
+        if ! scp -p -P  "${gerrit_port}" "${gerrit_username}@${gerrit_host}":hooks/commit-msg\
+                        "${git_dir}/hooks/commit-msg" >/dev/null 2>&1;then
+            die "Failed to \`scp\` the Change-Id hook" $err_scp_failed
+        fi
     fi
 }
 
